model: "whisper_large_v3_turbo"
max_seq_len: 448
resources:
  kv_cache:
    cpu_offload_pages: 128
  cross_kv_cache:
    cpu_offload_pages: 128
node_groups:
  - node_names: [audio_encoder, decoder]
    ranks: [0]
